### ISSUE TITLE
Add option to not generate interface

### ISSUE THREAD

**Issue by garysassano** [joao-mbn/react-extract#8]
Could you please add an option to avoid creating an interface and use the props directly like in WebStorm?

https://github.com/joao-mbn/react-extract/assets/10464497/ea3b52bc-b226-4f78-abe1-d882df34032d

**Comment by joao-mbn** [comment]
Hey @garysassano, let me see if I get it.

1. Inline type declaration + un-destructured props

```tsx
function Extracted(props: { onClick: () => void }) {
  return <MyComponent onClick={props.onClick} />
}
```

2. Inline type declaration + destructured props

```tsx
function Extracted({ onClick }: { onClick: () => void }) {
  return <MyComponent onClick={onClick} />
}
```

Are you asking for inline type declaration alone [2] or that plus keeping the props un-destructured, passing the full path [1]?

**Comment by garysassano** [comment]
Hi @joao-mbn, what I'm asking for is option 1 exactly.

**Comment by joao-mbn** [comment]
Just a quick feedback: I've been working on these features. Adding the inline type declaration was pretty straightforward, but keeping props undestructured not so much. I haven't shipped those yet because there are still some edge cases to handle.

When its ready I'll provide further instructions.

**Comment by joao-mbn** [comment]
@garysassano You'll be able to use this style in version 0.9.0. You can achieve that be changing the configuration options, setting `Type Declaration` to `inline` and `Destructure Props` to `false`.

According to the description in the README:

> #### "Type Declaration" | "reactExtract.typeDeclaration"
> 
> - **Description**: The type of type declaration to be used when extracting the component.
> 
> - **Accepts**: `"interface" | "type" | "inline"`
> 
> - **Default**: `"interface"`
> 
> ```typescript
> // interface
> interface ComponentProps {
>   // ...
> }
> 
> // type
> type ComponentProps = {
>   // ...
> };
> 
> // inline
> function Component(props: { onClick: () => void; value: number; options: number[] }) {
>   // ...
> }
> ```
> ...
> #### "Destructure Props" | "reactExtract.destructureProps"
> 
> - **Description**: Whether to do object destructure in the extracted component props parameter or not. If set to "false", the parameter will be named "props".
> 
> - **Accepts**: `"true" | "false"`
> 
> - **Default**: `"true"`
> 
> ```tsx
> // true
> function Component({ onClick, className }: ComponentProps) {
>   return <ChildComponent onClick={onClick} className={className} />;
> }
> 
> // false
> function Component(props: ComponentProps) {
>   return <ChildComponent onClick={props.onClick} className={props.className} />;
> }
> ```
> 
> _Note: If Destructure Props is set to false, but one of the props is a spread, props will be passed as destructured. Example:_
> 
> ```jsx
> // Before extraction
> function Parent() {
>   const childProps = {
>     className: 'myClass',
>     onClick: () => console.log('Clicked!')
>   };
> 
>   return <div {...childProps}>Child Component</div>;
> }
> 
> // After extraction
> function Parent() {
>   const childProps = {
>     className: 'myClass',
>     onClick: () => console.log('Clicked!')
>   };
> 
>   return <Child {...childProps} />;
> }
> 
> function Child({ ...childProps }) {
>   return <div {...childProps}>Child Component</div>;
> }
> ```
